#!/bin/bash
#
# Script de sauvegarde automatique pour SACRA
# Sauvegarde la base de données, le .env, et les fichiers importants
#

# Configuration
BACKUP_DIR="$HOME/saccra_backups"
APP_DIR="$HOME/saccra.fr"
DATE=$(date +"%Y%m%d_%H%M%S")
BACKUP_NAME="saccra_backup_${DATE}"

# Créer le dossier de backup s'il n'existe pas
mkdir -p "$BACKUP_DIR"
mkdir -p "$BACKUP_DIR/temp_$DATE"

echo "🚀 Démarrage du backup SACRA..."
echo "📅 Date: $(date)"
echo ""

# 1. Sauvegarder la base de données SQLite
echo "📦 Sauvegarde de la base de données..."
if [ -f "$APP_DIR/instance/sacra.db" ]; then
    cp "$APP_DIR/instance/sacra.db" "$BACKUP_DIR/temp_$DATE/sacra.db"
    echo "   ✅ Base de données sauvegardée"
else
    echo "   ⚠️  Base de données non trouvée dans instance/"
fi

# Chercher aussi à la racine
if [ -f "$APP_DIR/sacra.db" ]; then
    cp "$APP_DIR/sacra.db" "$BACKUP_DIR/temp_$DATE/sacra_root.db"
    echo "   ✅ Base de données (racine) sauvegardée"
fi

# 2. Sauvegarder le fichier .env
echo "🔐 Sauvegarde des variables d'environnement..."
if [ -f "$APP_DIR/.env" ]; then
    cp "$APP_DIR/.env" "$BACKUP_DIR/temp_$DATE/.env"
    echo "   ✅ Fichier .env sauvegardé"
else
    echo "   ⚠️  Fichier .env non trouvé"
fi

# 3. Sauvegarder .htaccess
echo "⚙️  Sauvegarde de la configuration Apache..."
if [ -f "$APP_DIR/.htaccess" ]; then
    cp "$APP_DIR/.htaccess" "$BACKUP_DIR/temp_$DATE/.htaccess"
    echo "   ✅ Fichier .htaccess sauvegardé"
fi

# 4. Créer un fichier d'informations
echo "📝 Création du fichier d'informations..."
cat > "$BACKUP_DIR/temp_$DATE/backup_info.txt" << EOF
SACRA Backup Information
========================
Date: $(date)
Hostname: $(hostname)
App Directory: $APP_DIR

Contenu de ce backup:
- Base de données SQLite (sacra.db)
- Variables d'environnement (.env)
- Configuration Apache (.htaccess)

Pour restaurer:
1. Copier sacra.db vers $APP_DIR/instance/
2. Copier .env vers $APP_DIR/
3. Copier .htaccess vers $APP_DIR/
4. Redémarrer l'application: pkill -9 -u $(whoami) python && touch $APP_DIR/tmp/restart.txt

Generated by backup.sh
EOF
echo "   ✅ Fichier d'informations créé"

# 5. Compresser le backup
echo "🗜️  Compression du backup..."
cd "$BACKUP_DIR"
tar -czf "${BACKUP_NAME}.tar.gz" "temp_$DATE"
rm -rf "temp_$DATE"
echo "   ✅ Backup compressé: ${BACKUP_NAME}.tar.gz"

# 6. Afficher la taille du backup
BACKUP_SIZE=$(du -h "$BACKUP_DIR/${BACKUP_NAME}.tar.gz" | cut -f1)
echo ""
echo "✅ Backup terminé avec succès!"
echo "📁 Fichier: $BACKUP_DIR/${BACKUP_NAME}.tar.gz"
echo "💾 Taille: $BACKUP_SIZE"
echo ""

# 7. Nettoyer les vieux backups (garder seulement les 10 derniers)
echo "🧹 Nettoyage des anciens backups..."
cd "$BACKUP_DIR"
ls -t saccra_backup_*.tar.gz | tail -n +11 | xargs -r rm
REMAINING=$(ls -1 saccra_backup_*.tar.gz 2>/dev/null | wc -l)
echo "   ✅ Backups conservés: $REMAINING"
echo ""

# 8. Liste des backups disponibles
echo "📋 Backups disponibles:"
ls -lh "$BACKUP_DIR"/saccra_backup_*.tar.gz 2>/dev/null | awk '{print "   " $9 " (" $5 ")"}'
echo ""
echo "🎉 Backup SACRA terminé!"
